# For use on local machine, run:
# docker-compose up -d
version: '3.1'

services:

  microblog:
    build: .
    restart: always
    ports:
      - 5000:5000
    env_file:
      - .env.prod
    environment:
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
